services:
- docker
python:
- 3.6
dist: trusty
stages:
- test
jobs:
  include:
    - name: Windows
      os: windows
      language: sh
      before_install:
        - choco install python3 --version 3.6.8
        - choco install make
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
      script:
        - make install-dev fast-test
      after_success:
        - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - $HOME/.cache/pip
